-- Total revenue generated by country

SELECT 
  c.Country, 
  ROUND(SUM(i.Total), 2) AS TotalRevenue
FROM 
  Customer c
JOIN 
  Invoice i ON c.CustomerId = i.CustomerId
GROUP BY 
  c.Country
ORDER BY 
  TotalRevenue DESC;

-- Results:
-- The USA generates the most revenue, followed by Canada, then France.
