-- Question: What is the total revenue generated by country?

SELECT 
  C.Country, 
  ROUND(SUM(I.Total), 2) AS TotalRevenue
FROM 
  Customer C
JOIN 
  Invoice I ON C.CustomerId = I.CustomerId
GROUP BY 
  C.Country
ORDER BY 
  TotalRevenue DESC;

-- Insight:
-- The USA generates the most revenue, followed by Canada, then France
