-- Total revenue generated by year

SELECT
  strftime('%Y', InvoiceDate) AS Year, 
  SUM(Total) AS Revenue
FROM 
  Invoice
GROUP BY 
  Year
ORDER BY 
  Year;

/*
Results:
2009	$449.46
2010	$481.45
2011	$469.58
2012	$477.53
2013	$450.58
*/
