-- Question: What is the total revenue generated by country?

SELECT 
  c.country, 
  ROUND(SUM(i.total), 2) AS TotalRevenue
FROM 
  customer c
JOIN 
  invoice i ON c.customerid = i.customerid
GROUP BY 
  c.country
ORDER BY 
  TotalRevenue DESC;

-- Insight:
-- The USA generates the most revenue, followed by Canada, then France
